<!doctype html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="title" content="<?php echo $this->title; ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <base href="<?php echo $this->base; ?>/">
        <link href="resources/css/bootstrap.min.css" rel="stylesheet" media="screen">
        <link href="resources/css/font-awesome.min.css" rel="stylesheet" media="screen">
        <link href="resources/css/layout.css" rel="stylesheet" media="screen">
        <link href="resources/css/contents.css" rel="stylesheet" media="screen">
        <link href="resources/css/errors.css" rel="stylesheet" media="screen">
        <!--[if lt IE 9]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <link href="resources/css/font-awesome-ie7.min.css" rel="stylesheet" media="screen" />
        <![endif]-->
        <title><?php echo $this->title; ?></title>
    </head>
    <body>
        <header>
            
        </header>
        <section>
            <?php echo $this->content; ?>
        </section>
        <footer>
            
        </footer>
        <script src="resources/js/jquery.min.js"></script>
        <script src="resources/js/bootstrap.min.js"></script>
        <script src="resources/js/khaus.functions.js"></script>
        <script src="resources/js/khaus.loader.js"></script>
        <?php if (file_exists('resources/js/khaus/' . $this->controller . '.js')): ?>
        <script src="resources/js/khaus/<?php echo $this->controller; ?>.js"></script>
        <?php endif; ?>
    </body>
</html>
<!-- 
Web developer: rhyudek1,
powered by Khaus Framework

@package     Khaus
@copyright   Copyright (c) 2013 rhyudek1. (https://github.com/niucode/khaus)
-->